spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/Snet2?stringtype=unspecified}
    username: snet
    password: snet
  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: SocialNetwork7SG@gmail.com
    password: $0c!ALnet

mail:
  debug: true

flyway:
  user: snet
  password: snet

server:
  port: 9000
  servlet:
    contextPath: /api/v1

#JWT Configuration
security:
  jwt:
    header: Authorization
    prefix: Bearer
    secret: JWTSecretKeyFor7GroupSocialNetwork082020
    expiration: 86400