create table messages (
    id int8 generated by default as identity,
    time timestamp with time zone not null,
    author_id int8 not null,
    recipient_id int8,
    message_text varchar(255) not null,
    read_status varchar(255) not null,
    dialog_id int8 not null,
    is_deleted boolean not null,
    primary key (id)
);

alter table if exists messages
    add constraint FK_MESSAGE_AUTHOR_ID
    foreign key (author_id) references person;

alter table if exists messages
    add constraint FK_MESSAGE_RECIPIENT_ID
    foreign key (recipient_id) references person;

alter table if exists messages
    add constraint FK_MESSAGE_DIALOG_ID
    foreign key (dialog_id) references dialogs;