create table person2dialogs (
    id int8 generated by default as identity,
    person_id int8 not null,
    dialog_id int8 not null,
    primary key (id)
);

alter table if exists person2dialogs
    add constraint FK_PERSON2DIALOG_PERSON_ID
    foreign key (person_id) references person;

alter table if exists person2dialogs
    add constraint FK_PERSON2DIALOG_DIALOG_ID
    foreign key (dialog_id) references dialogs;