create table post2tag
(
    id int8 generated by default as identity,
    post_id int8 not null,
    tag_id int8 not null,
    primary key (id)
);

alter table if exists post2tag
    add constraint FK_POST2TAG_POST_ID
    foreign key (post_id) references posts;

alter table if exists post2tag
    add constraint FK_POST2TAG_TAG_ID
    foreign key (tag_id) references tags;