create table post
(
    id int8 generated by default as identity,
    time timestamp with time zone,
    author_id int8 not null,
    title varchar(255) not null,
    post_text varchar(255) not null,
    is_blocked boolean not null,
    is_deleted boolean not null,
    primary key (id)
);

alter table if exists post
    add constraint FK_POST_PERSON_ID
    foreign key (author_id) references person;