create table comments (
    id int8 generated by default as identity,
    parent_id int8 not null,
    post_id int8 not null,
    comment_time timestamp with time zone,
    author_id int8 not null,
    comment_text varchar(255) not null,
    is_blocked boolean not null,
    primary key (id)
);

alter table if exists comments
    add constraint FK_COMMENT_PARENT_ID
    foreign key (parent_id) references comments;

alter table if exists comments
    add constraint FK_COMMENT_POST_ID
    foreign key (post_id) references posts;

alter table if exists comments
    add constraint FK_COMMENT_PERSON_ID
    foreign key (author_id) references person;