create table likes (
    id int8 generated by default as identity,
    time timestamp with time zone,
    person_id int8 not null,
    type varchar(255) not null,
    item_id int8 not null,
    primary key (id)
);

alter table if exists likes
    add constraint FK_LIKE_PERSON_ID
    foreign key (person_id) references person;