create table likes
(
    id        bigint generated by default as identity
        constraint likes_pkey
            primary key,
    item_id   bigint,
    like_type varchar(255),
    time      timestamp with time zone,
    person_id bigint not null
        constraint fk9qhcwajpah3s2chqvbjjfh744
            references person
);

alter table likes
    owner to snet;