create table post_likes (
    id int8 generated by default as identity,
    time timestamp with time zone,
    person_id int8 not null,
    post_id int8 not null,
    primary key (id)
);

alter table if exists post_likes
    add constraint FK_POST_LIKE_PERSON_ID
    foreign key (person_id) references person;

alter table if exists post_likes
    add constraint FK_POST_LIKE_POST_ID
    foreign key (post_id) references posts;