create table comment_likes (
    id int8 generated by default as identity,
    time timestamp with time zone,
    person_id int8 not null,
    comment_id int8 not null,
    primary key (id)
);

alter table if exists comment_likes
    add constraint FK_COMMENT_LIKE_PERSON_ID
    foreign key (person_id) references person;

alter table if exists comment_likes
    add constraint FK_POST_LIKE_COMMENT_ID
    foreign key (comment_id) references comments;