create table dialogs (
    id int8 generated by default as identity,
    owner_id int8 not null,
    unread_count int4 not null,
    is_deleted boolean not null,
    invite_code varchar(255),
    primary key (id)
);

alter table if exists dialogs
    add constraint FK_DIALOG_OWNER_ID
    foreign key (owner_id) references person;